services:
  db:
    image: mysql:8
    environment:
        DATABASE_HOST: store-db-1
        DATABASE_PORT: 3306
        SERVER_PORT: 8080
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: products
    expose: 
      - 3306
  app:
    image: faserver/store-service
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://store-db-1:3306/products
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
     - db
