apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
      - name: store-service
        image: faserver/store-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-service-service
spec:
  selector:
    app: store-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.ddl-auto: drop
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
---
spring.datasource.url:jdbc:mysql://127.0.0.1:3306/products
spring.datasource.username:root
spring.datasource.password:root
spring.datasource.driver-class-name:com.mysql.cj.jdbc.Driver