apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: compose2-jenkins
        image: faserver/storeapi:latest
        ports:
        - containerPort: 8080
